#!/usr/bin/env python
"""
Comments stdin to the GitHub PR that triggered the travis build.

Usage:
    flake8 | python travis_bot.py

Notes:
    The following enviromental variables need to be set:
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG
    - TRAVIS_BOT_GITHUB_TOKEN

    Moreover, TRAVIS_PULL_REQUEST needs to be set to the pull request's number
    and not 'false', which happens when a build is not a PR build.
"""

from __future__ import print_function

import os
import sys
import json
import requests

GITHUB_API_URL = 'https://api.github.com'


def comment_on_pull_request(repo_slug, pr_number, token, comment):
    """ Comment message on a given GitHub pull request. """
    url = '{api_url}/repos/{repo_slug}/issues/{number}/comments'.format(
        api_url=GITHUB_API_URL, repo_slug=repo_slug, number=pr_number)
    response = requests.post(url, data=json.dumps({'body': comment}),
                             headers={'Authorization': 'token ' + token})
    return response.json()


if __name__ == '__main__':
    REPO_SLUG = os.environ.get('TRAVIS_REPO_SLUG')
    PR_NUMBER = os.environ.get('TRAVIS_PULL_REQUEST')
    TOKEN = os.environ.get('TRAVIS_BOT_GITHUB_TOKEN')
    NO_RESULT_MESSAGE = os.environ.get('TRAVIS_BOT_NO_RESULTS_MSG', None)

    if not REPO_SLUG:
        print("TRAVIS_REPO_SLUG environment variable missing, are you running travis-bot on Travis CI?")
        sys.exit(1)

    if PR_NUMBER == "false":
        print("This build is not for a pull request, skipping creation of comment")
        sys.exit(0)

    if not TOKEN:
        print("Please set TRAVIS_BOT_GITHUB_TOKEN environment variable")
        sys.exit(1)

    results = sys.stdin.read().strip()
    message = (
        """
```
{results}
```
        """).format(results=results)

    if results:
        comment_on_pull_request(REPO_SLUG, PR_NUMBER, TOKEN, message)
    elif NO_RESULT_MESSAGE:
        comment_on_pull_request(REPO_SLUG, PR_NUMBER, TOKEN, NO_RESULT_MESSAGE)
